name: Cloud Continuous Integration

on:
  push:

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    build:
      strategy:
        matrix:
          platform: [windows-latest]
          python: ["3.8"]
      runs-on: ${{ matrix.platform }}
      name: Test
      steps:
        - name: Setup Miniconda
          uses: conda-incubator/setup-miniconda@v2.0.0
          with:
            activate-environment: autogluon_py3
            auto-update-conda: true
            python-version: ${{ matrix.python }}

        - name: test
          shell: bash -l {0}
          run: |
            conda install --channel conda-forge pygraphviz
            python -c "import pygraphviz"
          
        
