name: Cloud Continuous Integration

on:
  push:

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    build:
      strategy:
        matrix:
          platform: [windows-latest]
          python: ["3.8"]
      runs-on: ${{ matrix.platform }}
      name: Test
      steps:
        - name: graphviz
          uses: tlylt/install-graphviz@main
        - name: test
          shell: bash -l {0}
          run: |
            pip install pygraphviz
          
        
