name: Cloud Continuous Integration

on:
  push:

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if doc changes only
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            test:
              - 'README.md'
      - name: Skip if doc changes only
        if: steps.changes.outputs.docs == 'true'
        run:
          exit 0
      - name: Echo
        run:
          echo hi
