name: Cloud Continuous Integration

on:
  push:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      pr-sha:
        description: 'The pr-sha of which the slash command was dispatched'
        required: true
      branch_or_pr_number:
        description: 'dummy parameter to allow benchmark workflow to run'
        required: false

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    build:
      strategy:
        matrix:
          platform: [ubuntu-latest]
          python: ["3.8"]
      runs-on: ${{ matrix.platform }}
      name: Test
      steps:
        - name: Setup Miniconda
          uses: conda-incubator/setup-miniconda@v2.0.0
          with:
            activate-environment: autogluon_py3
            auto-update-conda: true
            python-version: ${{ matrix.python }}

        - name: test
          shell: bash -l {0}
          run: |
            conda install --channel conda-forge pygraphviz
            python -c "import pygraphviz"
          
        