name: Cloud Continuous Integration

on:
  push:

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  branch_check:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Fail on restricted branch
        # https://docs.github.com/en/actions/learn-github-actions/expressions#example-matching-an-array-of-strings
        if: contains(fromJSON('["cloud"]'), github.ref)
        run: exit 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check if doc changes only
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            test:
              - '!(*README.md)'
      - name: test
        uses: autogluon/autogluon/.github/actions/setup-env-vars
