name: Cloud Continuous Integration

on:
  push:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      pr-sha:
        description: 'The pr-sha of which the slash command was dispatched'
        required: true
      branch_or_pr_number:
        description: 'dummy parameter to allow benchmark workflow to run'
        required: false
      forked_branch:
        description: 'get branch name'
        required: true
      forked_repo:
        description: 'get fork repository'
        required: true

permissions:
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    build:
      strategy:
        matrix:
          platform: [ubuntu-latest]
          python: ["3.8"]
      runs-on: ${{ matrix.platform }}
      name: Test
      steps:
        - name: Setup Miniconda
          uses: conda-incubator/setup-miniconda@v2.0.0
          with:
            activate-environment: autogluon_py3
            auto-update-conda: true
            python-version: ${{ matrix.python }}
    viewEventPayload:
      runs-on: ubuntu-latest
      steps:
        - name: View GitHub Input Payload
          run: |
            echo "GitHub Input Payload:"
            echo "${{ toJson(github.events.ipnut) }}"
          
        